### ISSUE TITLE
GPU Memory

### ISSUE THREAD

**Issue by wenzhoulyu** [suyoung-lee/LDM#1]
I'm sorry to bother you. When I try your code, the 48g GPU Memory is still not enough. And I just try 2 works and 1 mixture work. I wonder how I sove the problem.

**Comment by suyoung-lee** [comment]
We ran 8 independent runs in parallel on a machine with 8 NVIDIA TITAN Xp (12G) GPUs and 128G RAM in total (one GPU assigned for each run).  There were no memory issues in that situation.

Did you have any problems running the baseline code, the variBAD (https://github.com/lmzintgraf/varibad) code? If you could explain the device and versions of libraries you are using, I may be able to help you solve the problem.

**Comment by wenzhoulyu** [comment]
I use the torch 1.6.0. I find that when I change the args2.eval_interval into 1, for every time the code products two eval envs, the gpu memory will increase.

**Comment by wenzhoulyu** [comment]
wow I'm sorry to bother you. I find that the gpu memory just  increases a few times. And it will turn stable. Thank you for your help.
