### ISSUE TITLE
action limit

### ISSUE THREAD

**Issue by wenzhoulyu** [suyoung-lee/LDM#2]
I‘m so sorry to bother you again. In my own env, I find the action will extremely beyond the action limitation. Then I check the policy act function, there is no limit for the output action which is sampled from the FixNormal. Should I add the action.tanh() in the code?
Here is the policy action I recorded. ![image](https://user-images.githubusercontent.com/47205275/161377458-a6496b4d-81fc-41ad-b1ec-a4091a3fb655.png).  My action limit is [-1,1]. But the action in your env (hf vel) seems to work well. Though the action sometimes will beyond the -1 or 1 too.

**Comment by wenzhoulyu** [comment]
I also found that there is a parameter named normalise_action in the args. When I turn it into True, the output action would still beyond the limitation sometimes

**Comment by suyoung-lee** [comment]
You may try to add tanh(), but I think the actions above the limit are adjusted by the environment anyway.

**Comment by wenzhoulyu** [comment]
I found that the code in oringal varibad has the args about "norm_actions_post_sampling", could it still work in LDM code? And I found the rew loss for my env is larger than 100, should I accelerate the convergence of rew encoder? Thank you so much for your  apply. That helps me a lot.

**Comment by suyoung-lee** [comment]
It seems that "norm_actions_post_sampling" is added after this[ commit ](https://github.com/lmzintgraf/varibad/commit/ff26cd48e4825528fdb18c590dfd38b25258c210). My code is based on the older version, but it should work in LDM code after changing the code according to the commit. 

I'm not sure how you modified the environment to gain high rew loss. Could you elaborate more on your modification and what you mean by "accelerating the convergence of rew encoder"?
